"""Generate the winmm.dll forwarding layer.

Reads the export names from the system's 32-bit winmm.dll and writes:
  winmm.def        - every export name mapped to a same-named stub
  stubs.S          - one `jmp *slot` per export (i386, AT&T syntax)
  winmm_names.h    - the name table that Init() resolves into g_winmm[] at load

The proxy then loads the real winmm from the system directory at runtime, so no copy
of Microsoft's DLL ships with the release.

Usage: python gen_stubs.py [path-to-32-bit-winmm.dll]
"""
import sys, pefile

src = sys.argv[1] if len(sys.argv) > 1 else r"C:\Windows\SysWOW64\winmm.dll"
pe = pefile.PE(src)
names = sorted(s.name.decode() for s in pe.DIRECTORY_ENTRY_EXPORT.symbols if s.name)

with open("winmm.def", "w", newline="\n") as f:
    f.write("LIBRARY winmm\nEXPORTS\n")
    for n in names:
        f.write(f"    {n} = stub_{n}\n")

with open("stubs.S", "w", newline="\n") as f:
    f.write("# Generated by gen_stubs.py - do not edit.\n")
    f.write("    .text\n")
    for i, n in enumerate(names):
        f.write(f"    .globl _stub_{n}\n_stub_{n}:\n    jmp *_g_winmm+{i * 4}\n")

with open("winmm_names.h", "w", newline="\n") as f:
    f.write("/* Generated by gen_stubs.py - do not edit. */\n")
    f.write(f"#define WINMM_NEXPORTS {len(names)}\n")
    f.write("static const char* const g_winmmNames[WINMM_NEXPORTS] = {\n")
    for n in names:
        f.write(f'    "{n}",\n')
    f.write("};\n")

print(f"{len(names)} exports from {src}")
